// Code generated by goderive DO NOT EDIT.

package db

// deriveFmapItemsNames returns a list where each element of the input list has been morphed by the input function.
func deriveFmapItemsNames(f func(*ItemRecord) string, list []*ItemRecord) []string {
	out := make([]string, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}
